<?php

// PLEASE DON'T CHANGE constant's for OPERATOR_TYPE
define('OPERATOR_TYPE_CASHIER',		1);
define('OPERATOR_TYPE_TECHNICIAN',	2);
define('OPERATOR_TYPE_ADMIN',		3);
define('OPERATOR_TYPE_LINUX_ADMIN',	4);

define('AUDIT_ACTION_LOGIN',	1);
define('AUDIT_ACTION_LOGOUT',	2);
define('AUDIT_ACTION_ADD',		3);
define('AUDIT_ACTION_UPDATE',	4);
define('AUDIT_ACTION_DELETE',	5);
define('AUDIT_ACTION_ENABLE',	6);
define('AUDIT_ACTION_DISABLE',	7);

define('AUDIT_RESOURCE_SYSTEM',			1);
define('AUDIT_RESOURCE_OPERATOR',		2);
define('AUDIT_RESOURCE_USER',			3);
define('AUDIT_RESOURCE_IP',				4);
define('AUDIT_RESOURCE_PPPOE',			5);
define('AUDIT_RESOURCE_STATIC_IP',		6);
define('AUDIT_RESOURCE_FREERADIUS',		7);
define('AUDIT_RESOURCE_PAYMENTS',		8);
?>
