ALTER TABLE operators DROP COLUMN IF EXISTS salt;
ALTER TABLE operators DROP COLUMN IF EXISTS refresh;
UPDATE operators SET passwd=MD5('sadmin') WHERE alias='sadmin';
UPDATE operators SET passwd=MD5('admin') WHERE alias='admin';
DROP TABLE IF EXISTS traffic;
DROP TABLE IF EXISTS static_ippool;
DROP TABLE IF EXISTS switches;
ALTER TABLE users DROP COLUMN IF EXISTS switchid;
ALTER TABLE users DROP COLUMN IF EXISTS pppoe;
ALTER TABLE payments DROP COLUMN IF EXISTS username;
DROP TABLE IF EXISTS radippool;
DROP TABLE IF EXISTS radreply;
DROP TABLE IF EXISTS radpostauth;

ALTER TABLE radacct DROP COLUMN IF EXISTS groupname;
ALTER TABLE radacct DROP COLUMN IF EXISTS realm;
ALTER TABLE radacct DROP COLUMN IF EXISTS nasportid;
ALTER TABLE radacct DROP COLUMN IF EXISTS nasporttype;
ALTER TABLE radacct DROP COLUMN IF EXISTS acctauthentic;
ALTER TABLE radacct DROP COLUMN IF EXISTS connectinfo_start;
ALTER TABLE radacct DROP COLUMN IF EXISTS connectinfo_stop;
ALTER TABLE radacct DROP COLUMN IF EXISTS calledstationid;
ALTER TABLE radacct DROP COLUMN IF EXISTS servicetype;
ALTER TABLE radacct DROP COLUMN IF EXISTS framedprotocol;
